#!/bin/bash

nexe index.js -t linux-x64 -o ./output/iot-discord-rpc-linux
nexe index.js -t macos-10.13.0 -o ./output/iot-discord-rpc-macos
nexe index.js -t win32-x86-10.13.0 -o ./output/iot-discord-rpc-win.exe
